### ISSUE TITLE
HTTP 500 error after login after update to v3

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/leantime_ynh#23]
![image](https://github.com/YunoHost-Apps/leantime_ynh/assets/19874562/a5b110ec-9de9-46db-ba82-cf72c1a0fbbd)

Clicking on the buttons doesn't change anything.

This is the stacktrace from `error.log`.

```
[18-Jan-2024 10:54:22 Etc/UTC] InvalidArgumentException: Unable to locate a class or view for component [widgets::moveableWidget]. in /var/www/leantime/vendor/illuminate/view/Compilers/ComponentTagCompiler.php:311
Stack trace:
#0 /var/www/leantime/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(235): Illuminate\View\Compilers\ComponentTagCompiler->componentClass()
#1 /var/www/leantime/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(156): Illuminate\View\Compilers\ComponentTagCompiler->componentString()
#2 [internal function]: Illuminate\View\Compilers\ComponentTagCompiler->Illuminate\View\Compilers\{closure}()
#3 /var/www/leantime/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(151): preg_replace_callback()
#4 /var/www/leantime/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(90): Illuminate\View\Compilers\ComponentTagCompiler->compileOpeningTags()
#5 /var/www/leantime/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(76): Illuminate\View\Compilers\ComponentTagCompiler->compileTags()
#6 /var/www/leantime/vendor/illuminate/view/Compilers/BladeCompiler.php(423): Illuminate\View\Compilers\ComponentTagCompiler->compile()
#7 /var/www/leantime/vendor/illuminate/view/Compilers/BladeCompiler.php(255): Illuminate\View\Compilers\BladeCompiler->compileComponentTags()
#8 /var/www/leantime/vendor/illuminate/view/Compilers/BladeCompiler.php(175): Illuminate\View\Compilers\BladeCompiler->compileString()
#9 /var/www/leantime/vendor/illuminate/view/Engines/CompilerEngine.php(62): Illuminate\View\Compilers\BladeCompiler->compile()
#10 /var/www/leantime/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#11 /var/www/leantime/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#12 /var/www/leantime/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#13 /var/www/leantime/app/Core/Template.php(504): Illuminate\View\View->render()
#14 /var/www/leantime/app/Domain/Dashboard/Controllers/Home.php(107): Leantime\Core\Template->display()
#15 /var/www/leantime/app/Core/Controller.php(82): Leantime\Domain\Dashboard\Controllers\Home->get()
#16 /var/www/leantime/app/Core/Controller.php(47): Leantime\Core\Controller->executeActions()
#17 [internal function]: Leantime\Core\Controller->__construct()
#18 /var/www/leantime/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#19 /var/www/leantime/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#20 /var/www/leantime/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#21 /var/www/leantime/app/Core/Frontcontroller.php(136): Illuminate\Container\Container->make()
#22 /var/www/leantime/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction()
#23 /var/www/leantime/app/Core/HttpKernel.php(62): Leantime\Core\Frontcontroller::dispatch()
#24 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}()
#25 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/leantime/app/Core/HttpKernel.php(62): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}()
#28 /var/www/leantime/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle()
#30 /var/www/leantime/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle()
#32 /var/www/leantime/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle()
#34 /var/www/leantime/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle()
#36 /var/www/leantime/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle()
#38 /var/www/leantime/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle()
#40 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/leantime/app/Core/HttpKernel.php(54): Illuminate\Pipeline\Pipeline->then()
#42 /var/www/leantime/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle()
#43 /var/www/leantime/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#44 /var/www/leantime/public/index.php(18): Leantime\Core\Bootloader->boot()
#45 {main}

```

Edit: Same bug as here: https://github.com/Leantime/leantime/issues/2193 

Edit2: Doesn't happen on fresh install of LeanTime version 3. So, must be an issue while upgrading.

**Comment by D4thToMS** [comment]
Any news on this issue? I just updated this morning from v2.4.7 to v3.0.2 and got exactly this issue.
Thanks!

**Comment by D4thToMS** [comment]
update 3.0.3 fixed the error 500 on my side thank you

**Comment by CodeShakingSheep** [comment]
Great that it worked for you @D4thToMS . I still have this error with Leantime 3.0.4 . So, I restored my backup of version 2.4.8 .

**Comment by D4thToMS** [comment]
@CodeShakingSheep sad to hear it doesn't for you, my last year experience with leantime is pretty scary and sadly I wouldn't recommend it (system administration wise), updates are Kamikaze

**Comment by mlvrai** [comment]
I had exactly the same error. Solved it by clearing browser history.

**Comment by CodeShakingSheep** [comment]
Thanks for the hint @mlvrai . It worked :raised_hands:
